export const tagsArray = [
        "Cloud Computing",
        "Solutions",
        "IT",
        "Network Security",
        "Audit",
        "SEO",
        "Optimization",
        "Marketing",
        "CMS",
        "Web Development",
        "Content",
        "Mobile App",
        "UI/UX",
        "Design",
        "Social Media",
        "Management",
        "Software",
        "Integration",
        "E-commerce",
        "Development",
        "Web",
        "Data Analytics",
        "AI",
        "Chatbot",
        "Virtual Reality",
        "Experience",
        "Blockchain",
        "CRM",
        "System",
        "Data",
        "Training",
        "Website",
        "Redesign",
        "Mobile",
        "App",
        "Cloud",
        "Migration",
        "Cybersecurity",
        "Tools",
        "Custom",
        "Smart Home",
        "Automation",
        "Technology",
        "E-Commerce",
        "Platform",
        "Payment",
        "Gateway",
        "ERP",
        "Data Warehouse",
        "Solution",
        "Customer Support",
        "Digital Marketing",
        "Campaign",
        "Strategy",
        "HR",
        "Video Streaming",
        "Service",
        "Augmented Reality",
        "Analytics",
        "Dashboard",
        "Mobile Payment"      
  ];


  export const tagStyles = {
    "Cloud Computing": "text-red-500 bg-red-100",
    "Solutions": "text-green-500 bg-green-100",
    "IT": "text-yellow-500 bg-yellow-100",
    "Network Security": "text-green-600 bg-green-100",
    "Audit": "text-orange-600 bg-orange-100",
    "SEO": "text-sky-500 bg-sky-100",
    "Optimization": "text-yellow-400 bg-yellow-100",
    "Marketing": "text-pink-400 bg-pink-100",
    "CMS": "text-green-500 bg-green-100",
    "Web Development": "text-indigo-500 bg-indigo-100",
    "Content": "text-blue-400 bg-blue-100",
    "Mobile App": "text-orange-400 bg-orange-100",
    "UI/UX": "text-pink-500 bg-pink-100",
    "Design": "text-purple-400 bg-purple-100",
    "Social Media": "text-indigo-400 bg-indigo-100",
    "Management": "text-green-400 bg-green-100",
    "Software": "text-gray-500 bg-gray-100",
    "Integration": "text-blue-400 bg-blue-100",
    "E-commerce": "text-emerald-500 bg-emerald-100",
    "Development": "text-lime-500 bg-lime-100",
    "Web": "text-gray-600 bg-gray-100",
    "Data Analytics": "text-blue-600 bg-blue-100",
    "AI": "text-red-500 bg-red-100",
    "Chatbot": "text-green-500 bg-green-100",
    "Virtual Reality": "text-purple-500 bg-purple-100",
    "Experience": "text-gray-400 bg-gray-100",
    "Blockchain": "text-blue-500 bg-blue-100",
    "CRM": "text-teal-600 bg-teal-100",
    "System": "text-orange-400 bg-orange-100",
    "Data": "text-cyan-500 bg-cyan-100",
    "Training": "text-yellow-600 bg-yellow-100",
    "Website": "text-gray-500 bg-gray-100",
    "Redesign": "text-teal-500 bg-teal-100",
    "Mobile": "text-orange-500 bg-orange-100",
    "App": "text-yellow-500 bg-yellow-100",
    "Cloud": "text-blue-400 bg-blue-100",
    "Migration": "text-red-400 bg-red-100",
    "Cybersecurity": "text-gray-600 bg-gray-100",
    "Tools": "text-purple-600 bg-purple-100",
    "Custom": "text-green-400 bg-green-100",
    "Smart Home": "text-blue-500 bg-blue-100",
    "Automation": "text-yellow-400 bg-yellow-100",
    "Technology": "text-blue-500 bg-blue-100",
    "E-Commerce": "text-emerald-500 bg-emerald-100",
    "Platform": "text-cyan-500 bg-cyan-100",
    "Payment": "text-orange-500 bg-orange-100",
    "Gateway": "text-red-500 bg-red-100",
    "ERP": "text-green-600 bg-green-100",
    "Data Warehouse": "text-gray-500 bg-gray-100",
    "Solution": "text-blue-400 bg-blue-100",
    "Customer Support": "text-teal-400 bg-teal-100",
    "Digital Marketing": "text-fuchsia-500 bg-fuchsia-100",
    "Campaign": "text-orange-600 bg-orange-100",
    "Strategy": "text-gray-500 bg-gray-100",
    "HR": "text-purple-500 bg-purple-100",
    "Video Streaming": "text-red-400 bg-red-100",
    "Service": "text-green-500 bg-green-100",
    "Augmented Reality": "text-teal-500 bg-teal-100",
    "Analytics": "text-blue-600 bg-blue-100",
    "Dashboard": "text-indigo-500 bg-indigo-100",
    "Mobile Payment": "text-pink-500 bg-pink-100"
};