export const tagsArray = [
    "Cloud Computing",
    "Solutions",
    "IT",
    "E-commerce",
    "Platform",
    "Development",
    "Cloud",
    "Migration",
    "Digital Marketing",
    "Strategy",
    "SEO",
    "CRM",
    "Implementation",
    "Business",
    "Network Security",
    "Audit",
    "CMS",
    "Web Development",
    "Content",
    "Social Media",
    "Management",
    "Marketing",
    "API",
    "Backend",
    "Mobile App",
    "UI/UX",
    "Design",
    "Software Integration",
    "Technology",
    "Redesign",
    "App Development",
    "iOS",
    "Android",
    "Optimization"
  ];